FROM node:18.18-slim

WORKDIR /usr/src/app
# --- NETFREE CERT INTSALL ---
    ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh 
    RUN cat  /home/netfree-unix-ca.sh | sh
    ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
    ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
    ENV SSL_CERT_FILE=/etc/ca-bundle.crt
    # --- END NETFREE CERT INTSALL ---
    
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

COPY prisma ./prisma

RUN yarn install --frozen-lockfile --ignore-engines

RUN yarn prisma:generate

COPY . .

RUN yarn build

RUN yarn install --production --frozen-lockfile

CMD ["node", "dist/main.api"]
