FROM node:18.18-slim

WORKDIR /usr/src/app
    
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./
COPY prisma ./prisma

RUN yarn install --frozen-lockfile --ignore-engines

RUN yarn prisma:generate

COPY . .

RUN yarn build

RUN yarn install --production --frozen-lockfile

CMD ["node", "dist/main.api"]
